// Attendre que la page soit complètement chargée
window.addEventListener('load', function () {

    // Le dictionnaire complet (je le réduis ici pour la lisibilité, mais gardez le vôtre !)
    const traductions = {
        'tench, Tinca tinca': 'tanche',
        'goldfish, Carassius auratus': 'poisson rouge',
        'great white shark, white shark, man-eater, man-eating shark, Carcharodon carcharias': 'grand requin blanc',
        'tiger shark, Galeocerdo cuvieri': 'requin tigre',
        'hammerhead, hammerhead shark': 'requin marteau',
        'electric ray, crampfish, numbfish, torpedo': 'raie électrique',
        'stingray': 'raie pastenague',
        'cock': 'coq',
        'hen': 'poule',
        'ostrich, Struthio camelus': 'autruche',
        'brambling, Fringilla montifringilla': 'pinson du nord',
        'goldfinch, Carduelis carduelis': 'chardonneret élégant',
        'house finch, linnet, Carpodacus mexicanus': 'roselin familier',
        'junco, snowbird': 'junco',
        'indigo bunting, indigo finch, indigo bird, Passerina cyanea': 'passerin indigo',
        'robin, American robin, Turdus migratorius': 'merle d\'Amérique',
        'bulbul': 'bulbul',
        'jay': 'geai',
        'magpie': 'pie',
        'chickadee': 'mésange',
        'water ouzel, dipper': 'cincle plongeur',
        'kite': 'milan',
        'bald eagle, American eagle, Haliaeetus leucocephalus': 'pygargue à tête blanche',
        'vulture': 'vautour',
        'great grey owl, great gray owl, Strix nebulosa': 'chouette lapone',
        'European fire salamander, Salamandra salamandra': 'salamandre tachetée',
        'common newt, Triturus vulgaris': 'triton commun',
        'eft': 'triton',
        'spotted salamander, Ambystoma maculatum': 'salamandre maculée',
        'axolotl, mud puppy, Ambystoma mexicanum': 'axolotl',
        'bullfrog, Rana catesbeiana': 'ouaouaron',
        'tree frog, tree-frog': 'rainette',
        'tailed frog, bell toad, ribbed toad, Ascaphus trui': 'grenouille-à-queue',
        'loggerhead, loggerhead turtle, Caretta caretta': 'tortue caouanne',
        'leatherback turtle, leathery turtle, Luth, Dermochelys coriacea': 'tortue luth',
        'mud turtle': 'cinosterne',
        'terrapin': 'malaclemmyde',
        'box turtle, box tortoise': 'tortue-boîte',
        'banded gecko': 'gecko à bandes',
        'common iguana, iguana, Iguana iguana': 'iguane vert',
        'American chameleon, anole, Anolis carolinensis': 'anolis vert',
        'whiptail, whiptail lizard': 'lézard à queue de fouet',
        'agama': 'agame',
        'frilled lizard, Chlamydosaurus kingi': 'lézard à collerette',
        'alligator lizard': 'gerrhonote',
        'Gila monster, Heloderma suspectum': 'monstre de Gila',
        'green lizard, Lacerta viridis': 'lézard vert',
        'African chameleon, Chamaeleo chamaeleon': 'caméléon commun',
        'Komodo dragon, Komodo lizard, dragon lizard, giant lizard, Varanus komodoensis': 'dragon de Komodo',
        'African crocodile, Nile crocodile, Crocodylus niloticus': 'crocodile du Nil',
        'American alligator, Alligator mississipiensis': 'alligator d\'Amérique',
        'triceratops': 'tricératops',
        'thunder snake, worm snake, Carphophis amoenus': 'serpent-tonnerre',
        'ringneck snake, ring-necked snake, ring snake': 'couleuvre à collier américaine',
        'hognose snake, puff adder, sand viper': 'hétérodon',
        'green snake, grass snake': 'couleuvre verte',
        'king snake, kingsnake': 'serpent-roi',
        'garter snake, grass snake': 'couleuvre',
        'water snake': 'serpent d\'eau',
        'vine snake': 'serpent-liane',
        'night snake, Hypsiglena torquata': 'serpent de nuit',
        'boa constrictor, Constrictor constrictor': 'boa constricteur',
        'rock python, rock snake, Python sebae': 'python de Seba',
        'Indian cobra, Naja naja': 'cobra indien',
        'green mamba': 'mamba vert',
        'sea snake': 'serpent de mer',
        'horned viper, cerastes, sand viper, horned asp, Cerastes cornutus': 'vipère à cornes',
        'diamondback, diamondback rattlesnake, Crotalus adamanteus': 'crotale diamantin',
        'sidewinder, horned rattlesnake, Crotalus cerastes': 'crotale cornu',
        'trilobite': 'trilobite',
        'harvestman, daddy longlegs, Phalangium opilio': 'faucheux',
        'scorpion': 'scorpion',
        'black and gold garden spider, Argiope aurantia': 'argiope aurantia',
        'barn spider, Araneus cavaticus': 'épeire des granges',
        'garden spider, Aranea diadema': 'épeire diadème',
        'black widow, Latrodectus mactans': 'veuve noire',
        'tarantula': 'tarentule',
        'wolf spider, hunting spider': 'araignée-loup',
        'tick': 'tique',
        'centipede': 'mille-pattes',
        'black grouse': 'tétras lyre',
        'ptarmigan': 'lagopède',
        'ruffed grouse, partridge, Bonasa umbellus': 'gélinotte huppée',
        'prairie chicken, prairie grouse, prairie fowl': 'tétras des prairies',
        'peacock': 'paon',
        'quail': 'caille',
        'partridge': 'perdrix',
        'African grey, African gray, Psittacus erithacus': 'perroquet jaco',
        'macaw': 'ara',
        'sulphur-crested cockatoo, Kakatoe galerita, Cacatua galerita': 'cacatoès à huppe jaune',
        'lorikeet': 'loriquet',
        'coucal': 'coucal',
        'bee eater': 'guêpier',
        'hornbill': 'calao',
        'hummingbird': 'colibri',
        'jacamar': 'jacamar',
        'toucan': 'toucan',
        'drake': 'canard mâle',
        'red-breasted merganser, Mergus serrator': 'harle huppé',
        'goose': 'oie',
        'black swan, Cygnus atratus': 'cygne noir',
        'tusker': 'éléphant à défenses',
        'echidna, spiny anteater, anteater': 'échidné',
        'platypus, duckbill, duckbilled platypus, duck-billed platypus, Ornithorhynchus anatinus': 'ornithorynque',
        'wallaby, brush kangaroo': 'wallaby',
        'koala, koala bear, kangaroo bear, native bear, Phascolarctos cinereus': 'koala',
        'wombat': 'wombat',
        'jellyfish': 'méduse',
        'sea anemone, anemone': 'anémone de mer',
        'brain coral': 'corail-cerveau',
        'flatworm, platyhelminth': 'ver plat',
        'nematode, nematode worm, roundworm': 'nématode',
        'conch': 'conque',
        'snail': 'escargot',
        'slug': 'limace',
        'sea slug, nudibranch': 'limace de mer',
        'chiton, coat-of-mail shell, sea cradle, polyplacophore': 'chiton',
        'chambered nautilus, pearly nautilus, nautilus': 'nautile',
        'Dungeness crab, Cancer magister': 'crabe dormeur du Pacifique',
        'rock crab, Cancer irroratus': 'crabe commun',
        'fiddler crab': 'crabe violoniste',
        'king crab, Alaska crab, Alaskan king crab, Alaska king crab, Paralithodes camtschatica': 'crabe royal',
        'American lobster, Northern lobster, Maine lobster, Homarus americanus': 'homard américain',
        'spiny lobster, langouste, rock lobster, crawfish, crayfish, sea crawfish': 'langouste',
        'crayfish, crawfish, crawdad, crawdaddy': 'écrevisse',
        'hermit crab': 'bernard-l\'hermite',
        'isopod': 'isopode',
        'white stork, Ciconia ciconia': 'cigogne blanche',
        'black stork, Ciconia nigra': 'cigogne noire',
        'spoonbill': 'spatule',
        'flamingo': 'flamant rose',
        'little blue heron, Egretta caerulea': 'aigrette bleue',
        'American egret, great white heron, Egretta albus': 'grande aigrette',
        'bittern': 'butor',
        'crane': 'grue (oiseau)',
        'limpkin, Aramus pictus': 'courlan brun',
        'European gallinule, Porphyrio porphyrio': 'talève sultane',
        'American coot, marsh hen, mud hen, water hen, Fulica americana': 'foulque d\'Amérique',
        'bustard': 'outarde',
        'ruddy turnstone, Arenaria interpres': 'tournepierre à collier',
        'red-backed sandpiper, dunlin, Erolia alpina': 'bécasseau variable',
        'redshank, Tringa totanus': 'chevalier gambette',
        'dowitcher': 'bécassin',
        'oystercatcher, oyster catcher': 'huîtrier',
        'pelican': 'pélican',
        'king penguin, Aptenodytes patagonica': 'manchot royal',
        'albatross, mollymawk': 'albatros',
        'grey whale, gray whale, devilfish, Eschrichtius gibbosus, Eschrichtius robustus': 'baleine grise',
        'killer whale, killer, orca, grampus, sea wolf, Orcinus orca': 'orque',
        'dugong, Dugong dugon': 'dugong',
        'sea lion': 'otarie',
        'Chihuahua': 'chihuahua',
        'Japanese spaniel': 'épagneul japonais',
        'Maltese dog, Maltese terrier, Maltese': 'bichon maltais',
        'Pekinese, Pekingese, Peke': 'pékinois',
        'Shih-Tzu': 'shih tzu',
        'Blenheim spaniel': 'épagneul nain anglais',
        'papillon': 'épagneul papillon',
        'toy terrier': 'toy terrier',
        'Rhodesian ridgeback': 'chien de Rhodésie à crête dorsale',
        'Afghan hound, Afghan': 'lévrier afghan',
        'basset, basset hound': 'basset hound',
        'beagle': 'beagle',
        'bloodhound, sleuthhound': 'chien de Saint-Hubert',
        'bluetick': 'bluetick coonhound',
        'black-and-tan coonhound': 'black and tan coonhound',
        'Walker hound, Walker foxhound': 'walker coonhound',
        'English foxhound': 'foxhound anglais',
        'redbone': 'redbone coonhound',
        'borzoi, Russian wolfhound': 'barzoï',
        'Irish wolfhound': 'lévrier irlandais',
        'Italian greyhound': 'levrette d\'Italie',
        'whippet': 'whippet',
        'Ibizan hound, Ibizan podenco': 'chien de garenne des Baléares',
        'Norwegian elkhound, elkhound': 'chien d\'élan norvégien',
        'otterhound, otter hound': 'otterhound',
        'Saluki, gazelle hound': 'saluki',
        'Scottish deerhound, deerhound': 'lévrier écossais',
        'Weimaraner': 'braque de Weimar',
        'Staffordshire bullterrier, Staffordshire bull terrier': 'Staffordshire bull terrier',
        'American Staffordshire terrier, Staffordshire terrier, American pit bull terrier, pit bull terrier': 'American Staffordshire terrier',
        'Bedlington terrier': 'Bedlington terrier',
        'Border terrier': 'Border terrier',
        'Kerry blue terrier': 'Kerry blue terrier',
        'Irish terrier': 'terrier irlandais',
        'Norfolk terrier': 'terrier de Norfolk',
        'Norwich terrier': 'terrier de Norwich',
        'Yorkshire terrier': 'Yorkshire terrier',
        'wire-haired fox terrier': 'fox-terrier à poil dur',
        'Lakeland terrier': 'Lakeland terrier',
        'Sealyham terrier, Sealyham': 'Sealyham terrier',
        'Airedale, Airedale terrier': 'Airedale terrier',
        'cairn, cairn terrier': 'cairn terrier',
        'Australian terrier': 'terrier australien',
        'Dandie Dinmont, Dandie Dinmont terrier': 'Dandie Dinmont terrier',
        'Boston bull, Boston terrier': 'terrier de Boston',
        'miniature schnauzer': 'schnauzer nain',
        'giant schnauzer': 'schnauzer géant',
        'standard schnauzer': 'schnauzer moyen',
        'Scotch terrier, Scottish terrier, Scottie': 'terrier écossais',
        'Tibetan terrier, chrysanthemum dog': 'terrier du Tibet',
        'silky terrier, Sydney silky': 'terrier australien soyeux',
        'soft-coated wheaten terrier': 'terrier irlandais à poil doux',
        'West Highland white terrier': 'West Highland white terrier',
        'Lhasa, Lhasa apso': 'Lhassa apso',
        'flat-coated retriever': 'retriever à poil plat',
        'curly-coated retriever': 'retriever à poil bouclé',
        'golden retriever': 'golden retriever',
        'Labrador retriever': 'labrador retriever',
        'Chesapeake Bay retriever': 'retriever de la baie de Chesapeake',
        'German short-haired pointer': 'braque allemand à poil court',
        'vizsla, Hungarian pointer': 'braque hongrois à poil court',
        'English setter': 'setter anglais',
        'Irish setter, red setter': 'setter irlandais',
        'Gordon setter': 'setter Gordon',
        'Brittany spaniel': 'épagneul breton',
        'clumber, clumber spaniel': 'clumber spaniel',
        'English springer, English springer spaniel': 'springer spaniel anglais',
        'Welsh springer spaniel': 'springer spaniel gallois',
        'cocker spaniel, English cocker spaniel, cocker': 'cocker spaniel anglais',
        'Sussex spaniel': 'sussex spaniel',
        'Irish water spaniel': 'épagneul d\'eau irlandais',
        'kuvasz': 'kuvasz',
        'schipperke': 'schipperke',
        'groenendael': 'groenendael',
        'malinois': 'malinois',
        'briard': 'briard',
        'kelpie': 'kelpie australien',
        'komondor': 'komondor',
        'Old English sheepdog, bobtail': 'bobtail',
        'Shetland sheepdog, Shetland, Sheltie': 'chien de berger des Shetland',
        'collie': 'colley',
        'Border collie': 'border collie',
        'Bouvier des Flandres, Bouviers des Flandres': 'bouvier des Flandres',
        'Rottweiler': 'rottweiler',
        'German shepherd, German shepherd dog, German police dog, alsatian': 'berger allemand',
        'Doberman, Doberman pinscher': 'dobermann',
        'miniature pinscher': 'pinscher nain',
        'Greater Swiss Mountain dog': 'grand bouvier suisse',
        'Bernese mountain dog': 'bouvier bernois',
        'Appenzeller': 'bouvier d\'Appenzell',
        'EntleBucher': 'bouvier de l\'Entlebuch',
        'boxer': 'boxer',
        'bull mastiff': 'bullmastiff',
        'Tibetan mastiff': 'dogue du Tibet',
        'French bulldog': 'bouledogue français',
        'Great Dane': 'dogue allemand',
        'Saint Bernard, St Bernard': 'saint-bernard',
        'Eskimo dog, husky': 'chien esquimau',
        'malamute, malemute, Alaskan malamute': 'malamute de l\'Alaska',
        'Siberian husky': 'husky de Sibérie',
        'dalmatian, coach dog, carriage dog': 'dalmatien',
        'affenpinscher, monkey pinscher, monkey dog': 'affenpinscher',
        'basenji': 'basenji',
        'pug, pug-dog': 'carlin',
        'Leonberg': 'leonberg',
        'Newfoundland, Newfoundland dog': 'terre-neuve',
        'Great Pyrenees': 'chien de montagne des Pyrénées',
        'Samoyed, Samoyede': 'samoyède',
        'Pomeranian': 'spitz nain',
        'chow, chow chow': 'chow-chow',
        'keeshond': 'keeshond',
        'Brabancon griffon': 'griffon brabançon',
        'Pembroke, Pembroke Welsh corgi': 'welsh corgi Pembroke',
        'Cardigan, Cardigan Welsh corgi': 'welsh corgi Cardigan',
        'toy poodle': 'caniche toy',
        'miniature poodle': 'caniche nain',
        'standard poodle': 'caniche standard',
        'Mexican hairless': 'chien nu mexicain',
        'timber wolf, grey wolf, gray wolf, Canis lupus': 'loup gris',
        'white wolf, Arctic wolf, Canis lupus tundrarum': 'loup arctique',
        'red wolf, maned wolf, Canis rufus, Canis niger': 'loup rouge',
        'coyote, prairie wolf, brush wolf, Canis latrans': 'coyote',
        'dingo, warrigal, warragal, Canis dingo': 'dingo',
        'dhole, Cuon alpinus': 'dhole',
        'African hunting dog, hyena dog, Cape hunting dog, Lycaon pictus': 'lycaon',
        'hyena, hyaena': 'hyène',
        'red fox, Vulpes vulpes': 'renard roux',
        'kit fox, Vulpes macrotis': 'renard nain',
        'Arctic fox, white fox, Alopex lagopus': 'renard polaire',
        'grey fox, gray fox, Urocyon cinereoargenteus': 'renard gris',
        'tabby, tabby cat': 'chat tigré',
        'tiger cat': 'chat-tigre',
        'Persian cat': 'chat persan',
        'Siamese cat, Siamese': 'chat siamois',
        'Egyptian cat': 'chat égyptien',
        'cougar, puma, catamount, mountain lion, painter, panther, Felis concolor': 'cougar',
        'lynx, catamount': 'lynx',
        'leopard, Panthera pardus': 'léopard',
        'snow leopard, ounce, Panthera uncia': 'léopard des neiges',
        'jaguar, panther, Panthera onca, Felis onca': 'jaguar',
        'lion, king of beasts, Panthera leo': 'lion',
        'tiger, Panthera tigris': 'tigre',
        'cheetah, chetah, Acinonyx jubatus': 'guépard',
        'brown bear, bruin, Ursus arctos': 'ours brun',
        'American black bear, black bear, Ursus americanus, Euarctos americanus': 'ours noir américain',
        'ice bear, polar bear, Ursus Maritimus, Thalarctos maritimus': 'ours polaire',
        'sloth bear, Melursus ursinus, Ursus ursinus': 'ours lippu',
        'mongoose': 'mangouste',
        'meerkat, suricate': 'suricate',
        'tiger beetle': 'cicindèle',
        'ladybug, ladybeetle, lady beetle, ladybird, ladybird beetle': 'coccinelle',
        'ground beetle, carabid beetle': 'carabe',
        'long-horned beetle, longicorn, longicorn beetle': 'longicorne',
        'leaf beetle, chrysomelid': 'chrysomèle',
        'dung beetle': 'bousier',
        'rhinoceros beetle': 'scarabée rhinocéros',
        'weevil': 'charançon',
        'fly': 'mouche',
        'bee': 'abeille',
        'ant, emmet, pismire': 'fourmi',
        'grasshopper, hopper': 'sauterelle',
        'cricket': 'grillon',
        'walking stick, walkingstick, stick insect': 'phasme',
        'cockroach, roach': 'cafard',
        'mantis, mantid': 'mante',
        'cicada, cicala': 'cigale',
        'leafhopper': 'cicadelle',
        'lacewing, lacewing fly': 'chrysope',
        'dragonfly, darning needle, devil\'s darning needle, sewing needle, snake feeder, snake doctor, mosquito hawk, skeeter hawk': 'libellule',
        'damselfly': 'demoiselle',
        'admiral': 'amiral',
        'ringlet, ringlet butterfly': 'tircis',
        'monarch, monarch butterfly, milkweed butterfly, Danaus plexippus': 'monarque',
        'cabbage butterfly': 'piéride du chou',
        'sulphur butterfly, sulfur butterfly': 'colias',
        'lycaenid, lycaenid butterfly': 'lycène',
        'starfish, sea star': 'étoile de mer',
        'sea urchin': 'oursin',
        'sea cucumber, holothurian': 'concombre de mer',
        'wood rabbit, cottontail, cottontail rabbit': 'lapin à queue blanche',
        'hare': 'lièvre',
        'Angora, Angora rabbit': 'lapin angora',
        'hamster': 'hamster',
        'porcupine, hedgehog': 'porc-épic',
        'fox squirrel, eastern fox squirrel, Sciurus niger': 'écureuil-renard',
        'marmot': 'marmotte',
        'beaver': 'castor',
        'guinea pig, Cavia cobaya': 'cochon d\'Inde',
        'sorrel': 'alezan',
        'zebra': 'zèbre',
        'hog, pig, grunter, squealer, Sus scrofa': 'cochon',
        'wild boar, boar, Sus scrofa': 'sanglier',
        'warthog': 'phacochère',
        'hippopotamus, hippo, river horse, Hippopotamus amphibius': 'hippopotame',
        'ox': 'bœuf',
        'water buffalo, water ox, Asiatic buffalo, Bubalus bubalis': 'buffle d\'eau',
        'bison': 'bison',
        'ram, tup': 'bélier',
        'bighorn, bighorn sheep, cimarron, Rocky Mountain bighorn, Rocky Mountain sheep, Ovis canadensis': 'mouflon canadien',
        'ibex, Capra ibex': 'bouquetin',
        'hartebeest': 'bubale',
        'impala, Aepyceros melampus': 'impala',
        'gazelle': 'gazelle',
        'Arabian camel, dromedary, Camelus dromedarius': 'dromadaire',
        'llama': 'lama',
        'weasel': 'belette',
        'mink': 'vison',
        'polecat, fitch, foulmart, foumart, Mustela putorius': 'putois',
        'black-footed ferret, ferret, Mustela nigripes': 'putois à pieds noirs',
        'otter': 'loutre',
        'skunk, polecat, wood pussy': 'moufette',
        'badger': 'blaireau',
        'armadillo': 'tatou',
        'three-toed sloth, ai, Bradypus tridactylus': 'paresseux à trois doigts',
        'orangutan, orang, Pongo pygmaeus': 'orang-outan',
        'gorilla, Gorilla gorilla': 'gorille',
        'chimpanzee, chimp, Pan troglodytes': 'chimpanzé',
        'gibbon, Hylobates lar': 'gibbon',
        'siamang, Hylobates syndactylus, Symphalangus syndactylus': 'siamang',
        'guenon, guenon monkey': 'cercopithèque',
        'patas, hussar monkey, Erythrocebus patas': 'singe patas',
        'baboon': 'babouin',
        'macaque': 'macaque',
        'langur': 'langur',
        'colobus, colobus monkey': 'colobe',
        'proboscis monkey, Nasalis larvatus': 'nasique',
        'marmoset': 'ouistiti',
        'capuchin, ringtail, Cebus capucinus': 'capucin',
        'howler monkey, howler': 'singe hurleur',
        'titi, titi monkey': 'titi',
        'spider monkey, Ateles geoffroyi': 'singe-araignée',
        'squirrel monkey, Saimiri sciureus': 'singe-écureuil',
        'Madagascar cat, ring-tailed lemur, Lemur catta': 'lémur catta',
        'indri, indris, Indri indri, Indri brevicaudatus': 'indri',
        'Indian elephant, Elephas maximus': 'éléphant d\'Asie',
        'African elephant, Loxodonta africana': 'éléphant d\'Afrique',
        'lesser panda, red panda, panda, bear cat, cat bear, Ailurus fulgens': 'petit panda',
        'giant panda, panda, panda bear, coon bear, Ailuropoda melanoleuca': 'panda géant',
        'barracouta, snoek': 'thyrsite',
        'eel': 'anguille',
        'coho, cohoe, coho salmon, blue jack, silver salmon, Oncorhynchus kisutch': 'saumon coho',
        'rock beauty, Holocanthus tricolor': 'poisson-ange tricolore',
        'anemone fish': 'poisson-clown',
        'sturgeon': 'esturgeon',
        'gar, garfish, garpike, billfish, Lepisosteus osseus': 'lépisosté osseux',
        'lionfish': 'poisson-lion',
        'puffer, pufferfish, blowfish, globefish': 'poisson-globe',
        'abacus': 'boulier',
        'abaya': 'abaya',
        'academic gown, academic robe, judge\'s robe': 'toge universitaire',
        'accordion, piano accordion, squeeze box': 'accordéon',
        'acoustic guitar': 'guitare acoustique',
        'aircraft carrier, carrier, flattop, attack aircraft carrier': 'porte-avions',
        'airliner': 'avion de ligne',
        'airship, dirigible': 'dirigeable',
        'altar': 'autel',
        'ambulance': 'ambulance',
        'amphibian, amphibious vehicle': 'véhicule amphibie',
        'analog clock': 'horloge analogique',
        'apiary, bee house': 'rucher',
        'apron': 'tablier',
        'ashcan, trash can, garbage can, wastebin, ash bin, ash-bin, ashbin, dustbin, trash barrel, trash bin': 'poubelle',
        'assault rifle, assault gun': 'fusil d\'assaut',
        'backpack, back pack, knapsack, packsack, rucksack, haversack': 'sac à dos',
        'bakery, bakeshop, bakehouse': 'boulangerie',
        'balance beam, beam': 'poutre d\'équilibre',
        'balloon': 'ballon',
        'ballpoint, ballpoint pen, ballpen, Biro': 'stylo à bille',
        'Band Aid': 'pansement',
        'banjo': 'banjo',
        'bannister, banister, balustrade, balusters, handrail': 'rampe d\'escalier',
        'barbell': 'haltère',
        'barber chair': 'fauteuil de barbier',
        'barbershop': 'salon de coiffure',
        'barn': 'grange',
        'barometer': 'baromètre',
        'barrel, cask': 'tonneau',
        'barrow, garden cart, lawn cart, wheelbarrow': 'brouette',
        'baseball': 'baseball',
        'basketball': 'basketball',
        'bassinet': 'couffin',
        'bassoon': 'basson',
        'bathing cap, swimming cap': 'bonnet de bain',
        'bath towel': 'serviette de bain',
        'bathtub, bathing tub, bath, tub': 'baignoire',
        'beach wagon, station wagon, wagon, estate car, beach waggon, station waggon, waggon': 'break',
        'beacon, lighthouse, beacon light, pharos': 'phare',
        'beaker': 'bécher',
        'bearskin, busby, shako': 'bonnet d\'ourson',
        'beer bottle': 'bouteille de bière',
        'beer glass': 'verre à bière',
        'bell cote, bell cot': 'campanile',
        'bib': 'bavoir',
        'bicycle-built-for-two, tandem bicycle, tandem': 'tandem',
        'bikini, two-piece': 'bikini',
        'binder, ring-binder': 'classeur',
        'binoculars, field glasses, opera glasses': 'jumelles',
        'birdhouse': 'nichoir',
        'boathouse': 'hangar à bateaux',
        'bobsled, bobsleigh, bob': 'bobsleigh',
        'bolo tie, bolo, bola tie, bola': 'cravate texane',
        'bonnet, poke bonnet': 'bonnet',
        'bookcase': 'bibliothèque (meuble)',
        'bookshop, bookstore, bookstall': 'librairie',
        'bottlecap': 'capsule de bouteille',
        'bow': 'arc',
        'bow tie, bow-tie, bowtie': 'nœud papillon',
        'brass, memorial tablet, plaque': 'plaque commémorative',
        'brassiere, bra, bandeau': 'soutien-gorge',
        'breakwater, groin, groyne, mole, bulwark, seawall, jetty': 'brise-lames',
        'breastplate, aegis, egis': 'cuirasse',
        'broom': 'balai',
        'bucket, pail': 'seau',
        'buckle': 'boucle',
        'bulletproof vest': 'gilet pare-balles',
        'bullet train, bullet': 'TGV',
        'butcher shop, meat market': 'boucherie',
        'cab, hack, taxi, taxicab': 'taxi',
        'caldron, cauldron': 'chaudron',
        'candle, taper, wax light': 'bougie',
        'cannon': 'canon',
        'canoe': 'canoë',
        'can opener, tin opener': 'ouvre-boîte',
        'cardigan': 'cardigan',
        'car mirror': 'rétroviseur de voiture',
        'carousel, carrousel, merry-go-round, roundabout, whirligig': 'carrousel',
        'carpenter\'s kit, tool kit': 'boîte à outils de menuisier',
        'carton': 'carton',
        'car wheel': 'roue de voiture',
        'cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, ATM': 'distributeur de billets',
        'cassette': 'cassette',
        'cassette player': 'lecteur de cassettes',
        'castle': 'château',
        'catamaran': 'catamaran',
        'CD player': 'lecteur CD',
        'cello, violoncello': 'violoncelle',
        'cellular telephone, cellular phone, cellphone, cell, mobile phone': 'téléphone portable',
        'chain': 'chaîne',
        'chainlink fence': 'clôture en mailles de chaîne',
        'chain mail, ring mail, mail, chain armor, chain armour, ring armor, ring armour': 'cotte de mailles',
        'chain saw, chainsaw': 'tronçonneuse',
        'chest': 'coffre',
        'chiffonier, commode': 'chiffonnier',
        'chime, bell, gong': 'carillon',
        'china cabinet, china closet': 'vaisselier',
        'Christmas stocking': 'chaussette de Noël',
        'church, church building': 'église',
        'cinema, movie theater, movie theatre, movie house, picture palace': 'cinéma',
        'cleaver, meat cleaver, chopper': 'hachoir',
        'cliff dwelling': 'habitation troglodytique',
        'cloak': 'cape',
        'clog, geta, patten, sabot': 'sabot',
        'cocktail shaker': 'shaker',
        'coffee mug': 'tasse à café',
        'coffeepot': 'cafetière',
        'coil, spiral, volute, whorl, helix': 'bobine',
        'combination lock': 'cadenas à combinaison',
        'computer keyboard, keypad': 'clavier d\'ordinateur',
        'confectionery, confectionary, candy store': 'confiserie',
        'container ship, containership, container vessel': 'porte-conteneurs',
        'convertible': 'décapotable',
        'corkscrew, bottle screw': 'tire-bouchon',
        'cornet, horn, trumpet, trump': 'cornet',
        'cowboy boot': 'botte de cowboy',
        'cowboy hat, ten-gallon hat': 'chapeau de cowboy',
        'cradle': 'berceau',
        'crane': 'grue (machine)',
        'crash helmet': 'casque de protection',
        'crate': 'caisse',
        'crib, cot': 'lit d\'enfant',
        'Crock Pot': 'mijoteuse',
        'croquet ball': 'boule de croquet',
        'crutch': 'béquille',
        'cuirass': 'cuirasse',
        'dam, dike, dyke': 'barrage',
        'desk': 'bureau',
        'desktop computer': 'ordinateur de bureau',
        'dial telephone, dial phone': 'téléphone à cadran',
        'diaper, nappy, napkin': 'couche',
        'digital clock': 'horloge numérique',
        'digital watch': 'montre numérique',
        'dining table, board': 'table à manger',
        'dishrag, dishcloth': 'torchon',
        'dishwasher, dish washer, dishwashing machine': 'lave-vaisselle',
        'disk brake, disc brake': 'frein à disque',
        'dock, dockage, docking facility': 'quai',
        'dogsled, dog sleigh, dog sledge': 'traîneau à chiens',
        'dome': 'dôme',
        'doormat, welcome mat': 'paillasson',
        'drilling platform, offshore rig': 'plateforme de forage',
        'drum, membranophone, tympan': 'tambour',
        'drumstick': 'baguette de tambour',
        'dumbbell': 'haltère',
        'Dutch oven': 'cocotte en fonte',
        'electric fan, blower': 'ventilateur électrique',
        'electric guitar': 'guitare électrique',
        'electric locomotive': 'locomotive électrique',
        'entertainment center': 'meuble TV',
        'envelope': 'enveloppe',
        'espresso maker': 'machine à expresso',
        'face powder': 'poudre pour le visage',
        'feather boa, boa': 'boa en plumes',
        'file, file cabinet, filing cabinet': 'classeur à tiroirs',
        'fireboat': 'bateau-pompe',
        'fire engine, fire truck': 'camion de pompiers',
        'fire screen, fireguard': 'pare-feu',
        'flagpole, flagstaff': 'mât de drapeau',
        'flute, transverse flute': 'flûte',
        'folding chair': 'chaise pliante',
        'football helmet': 'casque de football',
        'forklift': 'chariot élévateur',
        'fountain': 'fontaine',
        'fountain pen': 'stylo plume',
        'four-poster': 'lit à baldaquin',
        'freight car': 'wagon de marchandises',
        'French horn, horn': 'cor d\'harmonie',
        'frying pan, frypan, skillet': 'poêle à frire',
        'fur coat': 'manteau de fourrure',
        'garbage truck, dustcart': 'camion poubelle',
        'gasmask, respirator, gas helmet': 'masque à gaz',
        'gas pump, gasoline pump, petrol pump, island dispenser': 'pompe à essence',
        'goblet': 'gobelet',
        'go-kart': 'karting',
        'golf ball': 'balle de golf',
        'golfcart, golf cart': 'voiturette de golf',
        'gondola': 'gondole',
        'gong, tam-tam': 'gong',
        'gown': 'robe de soirée',
        'grand piano, grand': 'piano à queue',
        'greenhouse, nursery, glasshouse': 'serre',
        'grille, radiator grille': 'calandre',
        'grocery store, grocery, food market, market': 'épicerie',
        'guillotine': 'guillotine',
        'hair slide': 'barrette',
        'hair spray': 'laque pour cheveux',
        'half track': 'semi-chenillé',
        'hammer': 'marteau',
        'hamper': 'panier à linge',
        'hand blower, blow dryer, blow drier, hair dryer, hair drier': 'sèche-cheveux',
        'hand-held computer, hand-held device': 'ordinateur de poche',
        'handkerchief, hankie, hanky, hankey': 'mouchoir',
        'hard disc, hard disk, fixed disk': 'disque dur',
        'harmonica, mouth organ, harp, mouth harp': 'harmonica',
        'harp': 'harpe',
        'harvester, reaper': 'moissonneuse',
        'hatchet': 'hachette',
        'holster': 'étui d\'arme',
        'home theater, home theatre': 'home cinéma',
        'honeycomb': 'rayon de miel',
        'hook, claw': 'crochet',
        'hoopskirt, crinoline': 'crinoline',
        'horizontal bar, high bar': 'barre fixe',
        'horse cart, horse-cart': 'charrette à cheval',
        'hourglass': 'sablier',
        'iPod': 'iPod',
        'iron, smoothing iron': 'fer à repasser',
        'jack-o\'-lantern': 'citrouille d\'Halloween',
        'jean, blue jean, denim': 'jean',
        'jeep, landrover': 'jeep',
        'jersey, T-shirt, tee shirt': 'maillot',
        'jigsaw puzzle': 'puzzle',
        'jinrikisha, ricksha, rickshaw': 'pousse-pousse',
        'joystick': 'joystick',
        'kimono': 'kimono',
        'knee pad': 'genouillère',
        'knot': 'nœud',
        'lab coat, laboratory coat': 'blouse de laboratoire',
        'ladle': 'louche',
        'lampshade, lamp shade': 'abat-jour',
        'laptop, laptop computer': 'ordinateur portable',
        'lawn mower, mower': 'tondeuse à gazon',
        'lens cap, lens cover': 'bouchon d\'objectif',
        'letter opener, paper knife, paperknife': 'coupe-papier',
        'library': 'bibliothèque (lieu)',
        'lifeboat': 'canot de sauvetage',
        'lighter, light, igniter, ignitor': 'briquet',
        'limousine, limo': 'limousine',
        'liner, ocean liner': 'paquebot',
        'lipstick, lip rouge': 'rouge à lèvres',
        'Loafer': 'mocassin',
        'lotion': 'lotion',
        'loudspeaker, speaker, speaker unit, loudspeaker system, speaker system': 'haut-parleur',
        'loupe, jeweler\'s loupe': 'loupe',
        'lumbermill, sawmill': 'scierie',
        'magnetic compass': 'boussole magnétique',
        'mailbag, postbag': 'sac postal',
        'mailbox, letter box': 'boîte aux lettres',
        'maillot': 'maillot de bain',
        'maillot, tank suit': 'maillot de bain une pièce',
        'manhole cover': 'plaque d\'égout',
        'maraca': 'maraca',
        'marimba, xylophone': 'marimba',
        'mask': 'masque',
        'matchstick': 'allumette',
        'maypole': 'mât de mai',
        'maze, labyrinth': 'labyrinthe',
        'measuring cup': 'verre doseur',
        'medicine chest, medicine cabinet': 'armoire à pharmacie',
        'megalith, megalithic structure': 'mégalithe',
        'microphone, mike': 'microphone',
        'microwave, microwave oven': 'four à micro-ondes',
        'military uniform': 'uniforme militaire',
        'milk can': 'bidon de lait',
        'minibus': 'minibus',
        'miniskirt, mini': 'minijupe',
        'minivan': 'monospace',
        'missile': 'missile',
        'mitten': 'moufle',
        'mixing bowl': 'bol à mélanger',
        'mobile home, manufactured home': 'mobile home',
        'Model T': 'Ford T',
        'modem': 'modem',
        'monastery': 'monastère',
        'monitor': 'écran',
        'moped': 'cyclomoteur',
        'mortar': 'mortier',
        'mortarboard': 'toque de diplômé',
        'mosque': 'mosquée',
        'mosquito net': 'moustiquaire',
        'motor scooter, scooter': 'scooter',
        'mountain bike, all-terrain bike, off-roader': 'VTT',
        'mountain tent': 'tente de montagne',
        'mouse, computer mouse': 'souris d\'ordinateur',
        'mousetrap': 'piège à souris',
        'moving van': 'camion de déménagement',
        'muzzle': 'muselière',
        'nail': 'clou',
        'neck brace': 'minerve',
        'necklace': 'collier',
        'nipple': 'tétine',
        'notebook, notebook computer': 'ordinateur portable',
        'obelisk': 'obélisque',
        'oboe, hautboy, hautbois': 'hautbois',
        'ocarina, sweet potato': 'ocarina',
        'odometer, hodometer, mileometer, milometer': 'odomètre',
        'oil filter': 'filtre à huile',
        'organ, pipe organ': 'orgue',
        'oscillator': 'oscillateur',
        'overskirt': 'surjupe',
        'oxcart': 'char à bœufs',
        'oxygen mask': 'masque à oxygène',
        'packet': 'paquet',
        'paddle, boat paddle': 'pagaie',
        'paddlewheel, paddle wheel': 'roue à aubes',
        'padlock': 'cadenas',
        'paintbrush': 'pinceau',
        'pajama, pyjama, PJs, jammies': 'pyjama',
        'palace': 'palais',
        'panpipe, pandean pipe, syrinx': 'flûte de Pan',
        'paper towel': 'essuie-tout',
        'parachute, chute': 'parachute',
        'parallel bars, bars': 'barres parallèles',
        'park bench': 'banc public',
        'parking meter': 'parcmètre',
        'passenger car, coach, carriage': 'voiture de tourisme',
        'patio, terrace': 'patio',
        'pay-phone, pay-station': 'téléphone public',
        'pedestal, plinth, footstall': 'piédestal',
        'pencil box, pencil case': 'trousse',
        'pencil sharpener': 'taille-crayon',
        'perfume, essence': 'parfum',
        'Petri dish': 'boîte de Petri',
        'photocopier': 'photocopieur',
        'pick, plectrum, plectron': 'médiator',
        'pickelhaube': 'casque à pointe',
        'picket fence, paling': 'clôture à piquets',
        'pickup, pickup truck': 'pick-up',
        'pier': 'jetée',
        'piggy bank, penny bank': 'tirelire',
        'pill bottle': 'flacon de pilules',
        'pillow': 'oreiller',
        'ping-pong ball': 'balle de ping-pong',
        'pinwheel': 'moulinet',
        'pirate, pirate ship': 'bateau pirate',
        'pitcher, ewer': 'pichet',
        'plane, carpenter\'s plane, woodworking plane': 'rabot',
        'planetarium': 'planétarium',
        'plastic bag': 'sac en plastique',
        'plate rack': 'égouttoir à vaisselle',
        'plow, plough': 'charrue',
        'plunger, plumber\'s helper': 'ventouse',
        'Polaroid camera, Polaroid Land camera': 'appareil Polaroid',
        'pole': 'poteau',
        'police van, police wagon, paddy wagon, patrol wagon, wagon, black Maria': 'fourgon de police',
        'poncho': 'poncho',
        'pool table, billiard table, snooker table': 'table de billard',
        'pop bottle, soda bottle': 'bouteille de soda',
        'pot, flowerpot': 'pot de fleurs',
        'potter\'s wheel': 'tour de potier',
        'power drill': 'perceuse électrique',
        'prayer rug, prayer mat': 'tapis de prière',
        'printer': 'imprimante',
        'prison, prison house': 'prison',
        'projectile, missile': 'projectile',
        'projector': 'projecteur',
        'puck, hockey puck': 'palet de hockey',
        'punching bag, punch bag, punching ball, punchball': 'sac de frappe',
        'purse': 'sac à main',
        'quill, quill pen': 'plume d\'oie',
        'quilt, comforter, comfort, puff': 'couette',
        'racer, race car, racing car': 'voiture de course',
        'racket, racquet': 'raquette',
        'radiator': 'radiateur',
        'radio, wireless': 'radio',
        'radio telescope, radio reflector': 'radiotélescope',
        'rain barrel': 'tonneau de pluie',
        'recreational vehicle, RV, R.V.': 'camping-car',
        'reel': 'moulinet',
        'reflex camera': 'appareil photo reflex',
        'refrigerator, icebox': 'réfrigérateur',
        'remote control, remote': 'télécommande',
        'restaurant, eating house, eating place, eatery': 'restaurant',
        'revolver, six-gun, six-shooter': 'revolver',
        'rifle': 'fusil',
        'rocking chair, rocker': 'fauteuil à bascule',
        'rotisserie': 'rôtissoire',
        'rubber eraser, rubber, pencil eraser': 'gomme',
        'rugby ball': 'ballon de rugby',
        'rule, ruler': 'règle',
        'running shoe': 'chaussure de course',
        'safe': 'coffre-fort',
        'safety pin': 'épingle de sûreté',
        'saltshaker, salt shaker': 'salière',
        'sandal': 'sandale',
        'sarong': 'sarong',
        'sax, saxophone': 'saxophone',
        'scabbard': 'fourreau',
        'scale, weighing machine': 'balance',
        'school bus': 'bus scolaire',
        'schooner': 'goélette',
        'scoreboard': 'tableau d\'affichage',
        'screen, CRT screen': 'écran',
        'screw': 'vis',
        'screwdriver': 'tournevis',
        'seat belt, seatbelt': 'ceinture de sécurité',
        'sewing machine': 'machine à coudre',
        'shield, buckler': 'bouclier',
        'shoe shop, shoe-shop, shoe store': 'magasin de chaussures',
        'shoji': 'shoji',
        'shopping basket': 'panier d\'achats',
        'shopping cart': 'chariot de supermarché',
        'shovel': 'pelle',
        'shower cap': 'bonnet de douche',
        'shower curtain': 'rideau de douche',
        'ski': 'ski',
        'ski mask': 'masque de ski',
        'sleeping bag': 'sac de couchage',
        'slide rule, slipstick': 'règle à calcul',
        'sliding door': 'porte coulissante',
        'slot, one-armed bandit': 'machine à sous',
        'snorkel': 'tuba',
        'snowmobile': 'motoneige',
        'snowplow, snowplough': 'chasse-neige',
        'soap dispenser': 'distributeur de savon',
        'soccer ball': 'ballon de football',
        'sock': 'chaussette',
        'solar dish, solar collector, solar furnace': 'parabole solaire',
        'sombrero': 'sombrero',
        'soup bowl': 'bol à soupe',
        'space bar': 'barre d\'espace',
        'space heater': 'chauffage d\'appoint',
        'space shuttle': 'navette spatiale',
        'spatula': 'spatule',
        'speedboat': 'bateau à moteur',
        'spider web, spider\'s web': 'toile d\'araignée',
        'spindle': 'broche',
        'sports car, sport car': 'voiture de sport',
        'spotlight, spot': 'projecteur',
        'stage': 'scène',
        'steam locomotive': 'locomotive à vapeur',
        'steel arch bridge': 'pont en arc d\'acier',
        'steel drum': 'steel drum',
        'stethoscope': 'stéthoscope',
        'stole': 'étole',
        'stone wall': 'mur de pierre',
        'stopwatch, stop watch': 'chronomètre',
        'stove': 'cuisinière',
        'strainer': 'passoire',
        'streetcar, tram, tramcar, trolley, trolley car': 'tramway',
        'stretcher': 'civière',
        'studio couch, day bed': 'canapé-lit',
        'stupa, tope': 'stupa',
        'submarine, pigboat, sub, U-boat': 'sous-marin',
        'suit, suit of clothes': 'costume',
        'sundial': 'cadran solaire',
        'sunglass': 'lunettes de soleil',
        'sunglasses, dark glasses, shades': 'lunettes de soleil',
        'sunscreen, sunblock, sun blocker': 'crème solaire',
        'suspension bridge': 'pont suspendu',
        'swab, swob, mop': 'serpillière',
        'sweatshirt': 'sweat-shirt',
        'swimming trunks, bathing trunks': 'maillot de bain homme',
        'swing': 'balançoire',
        'switch, electric switch, electrical switch': 'interrupteur',
        'syringe': 'seringue',
        'table lamp': 'lampe de table',
        'tank, army tank, armored combat vehicle, armoured combat vehicle': 'char d\'assaut',
        'tape player': 'lecteur de bandes',
        'teapot': 'théière',
        'teddy, teddy bear': 'ours en peluche',
        'television, television system': 'télévision',
        'tennis ball': 'balle de tennis',
        'thatch, thatched roof': 'toit de chaume',
        'theater curtain, theatre curtain': 'rideau de théâtre',
        'thimble': 'dé à coudre',
        'thresher, thrasher, threshing machine': 'batteuse',
        'throne': 'trône',
        'tile roof': 'toit de tuiles',
        'toaster': 'grille-pain',
        'tobacco shop, tobacconist shop, tobacconist': 'bureau de tabac',
        'toilet seat': 'siège de toilette',
        'torch': 'torche',
        'totem pole': 'mât totémique',
        'tow truck, tow car, wrecker': 'dépanneuse',
        'toyshop': 'magasin de jouets',
        'tractor': 'tracteur',
        'trailer truck, tractor trailer, trucking rig, rig, articulated lorry, semi': 'semi-remorque',
        'tray': 'plateau',
        'trench coat': 'trench-coat',
        'tricycle, trike, velocipede': 'tricycle',
        'trimaran': 'trimaran',
        'tripod': 'trépied',
        'triumphal arch': 'arc de triomphe',
        'trolleybus, trolley coach, trackless trolley': 'trolleybus',
        'trombone': 'trombone',
        'tub, vat': 'cuve',
        'turnstile': 'tourniquet',
        'typewriter keyboard': 'clavier de machine à écrire',
        'umbrella': 'parapluie',
        'unicycle, monocycle': 'monocycle',
        'upright, upright piano': 'piano droit',
        'vacuum, vacuum cleaner': 'aspirateur',
        'vase': 'vase',
        'vault': 'voûte',
        'velvet': 'velours',
        'vending machine': 'distributeur automatique',
        'vestment': 'vêtement liturgique',
        'viaduct': 'viaduc',
        'violin, fiddle': 'violon',
        'volleyball': 'ballon de volley',
        'waffle iron': 'gaufrier',
        'wall clock': 'horloge murale',
        'wallet, billfold, notecase, pocketbook': 'portefeuille',
        'wardrobe, closet, press': 'armoire',
        'warplane, military plane': 'avion de guerre',
        'washbasin, handbasin, washbowl, lavatory, wash-hand basin': 'lavabo',
        'washer, automatic washer, washing machine': 'machine à laver',
        'water bottle': 'gourde',
        'water jug': 'carafe d\'eau',
        'water tower': 'château d\'eau',
        'whiskey jug': 'pichet à whisky',
        'whistle': 'sifflet',
        'wig': 'perruque',
        'window screen': 'moustiquaire de fenêtre',
        'window shade': 'store de fenêtre',
        'Windsor tie': 'cravate Windsor',
        'wine bottle': 'bouteille de vin',
        'wing': 'aile',
        'wok': 'wok',
        'wooden spoon': 'cuillère en bois',
        'wool, woolen, woollen': 'laine',
        'worm fence, snake fence, snake-rail fence, Virginia fence': 'clôture en zigzag',
        'wreck': 'épave',
        'yawl': 'yawl',
        'yurt': 'yourte',
        'web site, website, internet site, site': 'site web',
        'comic book': 'bande dessinée',
        'crossword puzzle, crossword': 'mots croisés',
        'street sign': 'panneau de signalisation',
        'traffic light, traffic signal, stoplight': 'feu de circulation',
        'book jacket, dust cover, dust jacket, dust wrapper': 'jaquette de livre',
        'menu': 'menu',
        'plate': 'assiette',
        'guacamole': 'guacamole',
        'consomme': 'consommé',
        'hot pot, hotpot': 'fondue chinoise',
        'trifle': 'trifle',
        'ice cream, icecream': 'crème glacée',
        'ice lolly, lolly, lollipop, popsicle': 'sucette glacée',
        'French loaf': 'baguette',
        'bagel, beigel': 'bagel',
        'pretzel': 'bretzel',
        'cheeseburger': 'cheeseburger',
        'hotdog, hot dog, red hot': 'hot-dog',
        'mashed potato': 'purée de pommes de terre',
        'head cabbage': 'chou pommé',
        'broccoli': 'brocoli',
        'cauliflower': 'chou-fleur',
        'zucchini, courgette': 'courgette',
        'spaghetti squash': 'courge spaghetti',
        'acorn squash': 'courge poivrée',
        'butternut squash': 'courge butternut',
        'cucumber, cuke': 'concombre',
        'artichoke, globe artichoke': 'artichaut',
        'bell pepper': 'poivron',
        'cardoon': 'cardon',
        'mushroom': 'champignon',
        'Granny Smith': 'pomme Granny Smith',
        'strawberry': 'fraise',
        'orange': 'orange',
        'lemon': 'citron',
        'fig': 'figue',
        'pineapple, ananas': 'ananas',
        'banana': 'banane',
        'jackfruit, jak, jack': 'jacquier',
        'custard apple': 'anone',
        'pomegranate': 'grenade',
        'hay': 'foin',
        'carbonara': 'carbonara',
        'chocolate sauce, chocolate syrup': 'sauce au chocolat',
        'dough': 'pâte',
        'meat loaf, meatloaf': 'pain de viande',
        'pizza, pizza pie': 'pizza',
        'potpie': 'tourte',
        'burrito': 'burrito',
        'red wine': 'vin rouge',
        'espresso': 'espresso',
        'cup': 'tasse',
        'eggnog': 'lait de poule',
        'alp': 'alpe',
        'bubble': 'bulle',
        'cliff, drop, drop-off': 'falaise',
        'coral reef': 'récif corallien',
        'geyser': 'geyser',
        'lakeside, lakeshore': 'bord de lac',
        'promontory, headland, head, foreland': 'promontoire',
        'sandbar, sand bar': 'banc de sable',
        'seashore, coast, seacoast, sea-coast': 'bord de mer',
        'valley, vale': 'vallée',
        'volcano': 'volcan',
        'ballplayer, baseball player': 'joueur de baseball',
        'groom, bridegroom': 'marié',
        'scuba diver': 'plongeur',
        'rapeseed': 'colza',
        'daisy': 'pâquerette',
        'yellow lady\'s slipper, yellow lady-slipper, Cypripedium calceolus, Cypripedium parviflorum': 'sabot de Vénus jaune',
        'corn': 'maïs',
        'acorn': 'gland',
        'hip, rose hip, rosehip': 'cynorhodon',
        'buckeye, horse chestnut, conker': 'marron d\'Inde',
        'coral fungus': 'clavaire',
        'agaric': 'agaric',
        'gyromitra': 'gyromitre',
        'stinkhorn, carrion fungus': 'satyre puant',
        'earthstar': 'géastre',
        'hen-of-the-woods, hen of the woods, Polyporus frondosus, Grifola frondosa': 'polypore en touffes',
        'bolete': 'cèpe',
        'ear, spike, capitulum': 'épi',
        'toilet tissue, toilet paper, bathroom tissue': 'papier toilette'
    };

    // 1. Récupérer les éléments HTML
    const video = document.getElementById('video');
    const resultatElement = document.getElementById('resultat');
    const descriptionElement = document.getElementById('description');
    
    let classifier;
    let objetActuel = null;

    // 2. Fonction d'initialisation (setup)
    async function setup() {
        try {
            const stream = await navigator.mediaDevices.getUserMedia({ video: true });
            video.srcObject = stream;
            await new Promise((resolve) => {
                video.onloadedmetadata = () => resolve();
            });
            classifier = await ml5.imageClassifier('MobileNet');
            resultatElement.innerText = "Prêt !";
            classifyLoop();
        } catch (err) {
            console.error("Erreur critique lors de l'initialisation : ", err);
            resultatElement.innerText = "Erreur.";
        }
    }

    // Fonction pour interroger l'API de Wikipédia (MISE À JOUR)
    async function fetchWikipediaDescription(termeDeRecherche) {
        
        // ===================================================================
        // LA MODIFICATION EST ICI : on ajoute "&exsentences=2"
        // pour limiter le résumé à 2 phrases.
        // ===================================================================
        const endpoint = `https://fr.wikipedia.org/w/api.php?action=query&prop=extracts&exsentences=2&exintro&explaintext&format=json&origin=*&titles=${encodeURIComponent(termeDeRecherche)}`;
        
        try {
            const response = await fetch(endpoint);
            const data = await response.json();
            const pages = data.query.pages;
            const pageId = Object.keys(pages)[0];
            
            if (pageId !== '-1') {
                const extract = pages[pageId].extract;
                // Si l'extrait est vide même après la requête, on affiche un message par défaut.
                return extract || "Aucun résumé disponible pour cet article.";
            } else {
                return "Je ne connais pas cet objet. Impossible de trouver une page Wikipédia.";
            }
        } catch (error) {
            console.error("Erreur de l'API Wikipédia:", error);
            return "Impossible de charger la description.";
        }
    }

    // 3. La boucle de classification (inchangée)
    async function classifyLoop() {
        const results = await classifier.classify(video);
        const prediction = results[0];

        if (prediction.label !== objetActuel) {
            objetActuel = prediction.label;

            const englishLabelKey = prediction.label;
            const nomAffiche = traductions[englishLabelKey] || englishLabelKey.split(',')[0];

            resultatElement.innerText = `${nomAffiche} (${(prediction.confidence * 100).toFixed(0)}%)`;
            descriptionElement.innerText = "Recherche de la description...";
            
            const description = await fetchWikipediaDescription(nomAffiche);
            descriptionElement.innerText = description;
        }
        
        classifyLoop();
    }

    // Lancer tout le processus
    setup();
});
